1. 어떤게 생존률과 가장 근접한지 모르기 때문에 모든 값을 시각화해서 직접 확인

2. Family size 를 넣는 값은 값이 일정하지 않기 때문에 빼고 "SEX"와 "Age"의 값만 사용 하는 것으로 변경

3. accuracy 뽑아내는 것까지가 목표.

4. 도출된 결과: 여성의 경우 나이가 많을 수록 생존율이 높아지지만 남성의 경우 나이가 적을 수록 생존율이 높아진다.

5. 생존율 순서: 늙은 여성 > 젊은 여성 > 젊은 남성 > 늙은 남성 순으로 뽑 을 수 있다.